/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5d0cbc58f311412fe6ea51bc
*
* You will get 10% discount for each one of your friends
* 
*/
package com.totvs.template.Domain.Dto.Security.Roles;

import com.totvs.template.Domain.Dto.Base.EntityBaseDto;
import com.totvs.template.Domain.Dto.Security.Users.UserDto;
import lombok.Getter;
import lombok.Setter;

public class RoleDto extends EntityBaseDto {

    @Getter @Setter
    private UserDto user;
    @Getter @Setter
    private String role;
}
